// Stock Price Center API
// Read cached market data generated by stockprice/scripts/update-price.js

import fs from "fs";
import path from "path";

export default function handler(req, res) {
  try {
    const file = path.join(process.cwd(), "stockprice", "data", "latest-price.json");
    if (!fs.existsSync(file)) {
      return res.status(404).json({
        error: "price cache not found",
        file
      });
    }

    const data = JSON.parse(fs.readFileSync(file, "utf8"));
    res.status(200).json(data);
  } catch (err) {
    res.status(500).json({
      error: err.message
    });
  }
}
